# Generated by Django 4.2.5 on 2023-10-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_medicaltestinquiries_examinationorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaltestinquiries',
            old_name='paasword',
            new_name='password',
        ),
    ]
