# Generated by Django 4.2.5 on 2023-10-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_rename_paasword_medicaltestinquiries_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('access_time', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('initial_exam_date', models.DateField()),
                ('final_exam_date', models.DateField()),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
